name: GitHub Readme YouTube Cards
on:
  schedule:
    # Update every friday
    - cron: "0 0 * * FRI"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: 

# La primera vez es de manera manual
# https://youtu.be/btlEy8nGOrY
# https://github.com/CondorCoders/github-readme-profile